sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        RjZ3281Gia/SVAceZAroCvCzBL3Fe0k4BjOnEVQZGAG5DMHeNFPy4uErmLbWAahsQ4mikzhZ23nePpwVek+aYlBp+eBlVZ7I2XqSPywTAa7ZVwstNflrI0yNoVsg/Vz578L+IukNWyPVFxyvf531pm1of1h+YiDofZ0d+gFWJ9nctDdfl5MgDsVTvUNk3yhj3iUZw+f3YERFL8kngPnzcwhTQ5mN7JLBcrdLC7zcuV9EER+xDShTzxSknTYUhmAoZ1uQa4oAWZh9F7rDcvAP6785cuCnurR5U6/ur8WCzYrKYXv1QUEuhCNqqhPE5tgXSeZD+k3h+ufq9YYi8FXs4zQxoIenjKser8eeTzXuiOCxMHXEAVaSeOkhRt26NW3Dx/vk1qIJWMenlrJk4LX0VLbsU98U8Q2JMkCqY1RlAaL1+9v2fkt33ADVr+33kHEnpGdvMKdNKneHrMFTQO5vTS5S76sLkiMJJPouYu+yBwEKGYRbI3dIR/2Z5t4jP8VjMfyXepPw4xrGjTXxgjQw3cjVxTGeLajhwdm7yla3U+hHcJXoiafL4RXy5n2yKCmuQzOI7PB6LYt3Cx05pY7E7BucrV+F2c+c+8oKtzHBxYlD+2E5qxEeUdEGZsnfl37Zpf20XZSX9CPz7Ex7YJtOhMOJrDk1XYZ93m5HQgl5rb0=
    - secure: >-
        o1ULmKUQksWISiHHh97F4DelBCPhwigudqC7jH99vXebtOFhPuhQATZ6crJrgsr8Yy9UT9Vv+jkn2fVhx/79CymmEy8i5VMdmgeyHtQMf2yHpoGJKRhfE6w0+GlYp+l3qhJYlusqllycDo0wTtHp/7473mqeRlsyNdjsELaqs7laeHw045qzXIjpDtIUFLLrQYqbbCNmQa6Ywv79Uhk5IsxYc7VtjDXhRCwxNZvezxPCOr0vv9DglFZCiG6jPd1v9mFRPKUt6bYhDHWfxapNjj5OyQBma6s5GCGOcI3WBCv1tlT6QqZ7OwcccnuV9Q0GyM6MzzAyieUYDDbQbV6c3kQ7jvRulUxWh8hIaEksUiefqL7ClieflJMLiDIDYJpSr0mvMgYb1kUPOVAdWwzRQ7TdJcAFYm8X5SCj4juIittspK/Knv5zhG4ElTmxg8AmtJGnCmYzaxrmir3wicoWHeqbofzvVJpytZXPEk4B4Tl3eQVwfHCSDYEOzBKJ8/chPOrKW3tZq0h+UZdzY78P9jUoLfWrwXoNAPjH62xkWKNy5bWG4oodBQwsw6CQuauLqPmYuJC1/IRvTtJqqYEBrn4WtCr9cMd/88FhKqbUakgXzxRCj4lda7R2LDBirAlZ0s0TmK/4+GB+pxarW9TE4pYFqn8G7LVC3NQIO9Uhdoo=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
