sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        uvFoiQzccN54FfXYOZ/BylhDK0uH+ZMHYPLhYuJpd7j4UYZEys31PKsK24zT1mJ+kaXCplIX1hzvOX/344nff6MKLvUkUWfmWRlo+VOOW36MEWmy9KUIzDW9sxEEzQHT/7VyJq0ohmi98LEWcLZor2VdpUmez7XsLsmRHHUfdfEww20wi2SK5e0UqJMX6g5WjReJ2Q7QAhpB6DtmFubAr+cyeS0UYSqZITRgaLLtM1LblgEFz8nkJ16uBLCBQe2ZMGcEJKP1dKMfvyuhsaszfpUBY8VOHRuxzZZjVkGc8lTX+Q4ioe+2kDw1gBC+h+23Ret0QzUajjdYO6TG7+JnhXnFstbQ9Df8YI2eAYR0Sd3NTPey1HKo+cSqVytavW/TcgVolJVUd/apnEzcUOelSjyjiuU7FOnByOT41QhARMpQYsMll5tp1NaeX94YsJ87yEepus+tkxesp0Gdb8qTnnVFdqjb6oK4onVQPSV7kf/FoeFUt591KagFQvCz2qZ88WkADBSNLURBFki2qVAmkIjsLYllVcobvnmFRC0shCHBZBRqqTrHBAY+yaXSPKf2N6GjkI4SNpvi4BbOzwwxTyDwqdSOkw/TZV0oUbGJX9Z6GLyAAprSIuRPIx6V48OYFHTGQ9BvMRkIj/Ema6o+6GxEIHkjHlvY1CO437ySfvo=
    - secure: >-
        SyQxatxmVfaEQSzuKHGeZWw3IMiVW/hDP2wgoY8mvQLU7rIU7IdRdqZTphyrKNcWrI6PfjzjHcaixkcm3KdnQNEMyRvCFVmW5IiCeMHg69P2E4d/7Y1K6+RnBW+EDMShukBQ6dU9+qAAxlALIz3nTrsrX1L7ckjyinWSyjeZjpQ5uPeqQW5HyD4pz9Oo6UtGdKn01hgSV1m+s4wa/K81uFRnM8nsdA/MCSz0VUc5tYNP6hcJ/6yLMoN7/cLB+cCcuik4L0C9OofAqQTdqLt1soHVNigGo2my7VIOIjqijBlZDpA8axFuIEo3cvKVXp9vwaEmDuBStWQ1W+xAL/iYBpIfr4sS41wCABYkhlXuzR9us6yx/Zoehlr/FmhbOijubqqgNdcHLnzmQ/j3TYhmDUZORds8fWkexXEzzJsPNgcj0QkSq7tj7prpgNwucOl8KZggshXNE1MTIMW53jBVM5DzRgmLFM7LqhvjvM4YGoqCAinRiVHDSMEJN3jqSW8cvpopYrbaXGm+TMU4aIXyv7iDgBl8MZ2WLeS/g1/VaigZUCRsYLXgS3vAQPUqg+MFUBNJEGtMnetUmFEEJVbd/yyXUQBp9dyii2C6Wf+i1N1C99n1Rinmc4qC67JD4Ctx6PiTAb54mWTRAQAXBvNVW1zKs4U0rFMpaUNXPTm1MR8=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
