sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        JS88INM/uUJ/P6HSs4csueyEuqLVUjAr8tEBUWE5VIdSxSlhN95j80WTETL3bEXYEfL4LJLtWw645bdv2GpqpDDosArqN2/PlwNXunvJ143mFxWuLNb1quLu4SJvPJvgrkN/YhcQp1ZzXUVqWrOEuWjr4uZ7u6Hivc09trT/5Gle35nnK86rgegslv/nyQYkcDB4/zF+mwUKdkK67ESfiQOUHZTI1rLoGkGD+v5BEdNRNSL5peA7R4Sl86KIYQV2p0dhWEb+6Z+nMU4CSlLW2bjigymtlnybl6i6iBl6euYNabygGepv5gYemBWb47pk1s36zX3906HAIwsCTlWAEEBcfsMiBGOETVAMQNnawa7vhaY+kZcBFheMbSvu4CitiJYfPEJ71w+dSnrutJtUD/UY+4KBhNMqKyo/1zaXi2+ldcVOEazg8iYmw2mGV5gzZpTCJRiFJX1hhiP5qgYSoDtBC0moFwwgvou3mvGwXeM8I1alJXnPBVAdC5+WWivTPCUHtAcJFFEHvb+0tsMKYhsP7+L3N+/kuY2jBdio/p1BXD723aPCHYl60w0YNmC97cdU27Bn7S+9DHv1enViNr9428KJrkhiDqcepvxmxwN1jPU9+vdYyUxAL8uFcIlgcbj7YWtIG5w/WHfeOBR8dVt/k4h8Xo8CCu1sk3g3WfQ=
    - secure: >-
        ij6DMxLGONVuxoVB11Sy7wslKrci5jmSwzR/c5MwWf8BDsfgc1hoieSK1PKPKmY+mNg9ysvj6+7I3nwp0peIHTQQ2/9Z78G7EQ8KafUC0alxQVIMpgmPaKCmpaiob6zy5Kq2LkeR5royz13eu1A+XUAAa/VTbwiA7XYExTidGj7g10myiJvPq54D/k/A9q/1idhHziKTgjmt1yiRgwhQCtaJ9IrxEU2z2WqdupLnnAVpRZM5qMHj5PrvSwdz8xoKnCa3Ri07iOQkbRKxSKPAcmwlrJ2a89LLMPvGDp+PvBGUpYH4c15Xghzzfje4lvNPAZXovCOR+1K1FlZ86mSLi0l4ACq0jj8cvwPP46O+wILUvaxd2R4ZkS72EDR7E/TCUDp2nizw/yKjP6lUUIbRpA8OBBx33zufAmQy9rh6GUqZXwnCQDDj/X91daHLQlV6Xc7IR8bFi4Kr4Wq0pzo/pIRjUQs2vaZvir22dQabvfUwIOAq1foyW0/oL6e87u8vPikBrZS6px43WC9Qukcpz3MD8zOB423Cau0650zVuGqr5nDeA6lgaRigzIliBLSL+m4Uv25OIX1O4pqb4dpumG+TAacLvd6T1qMobUbipqox7RtlobmwRp/4nTOWrFv5ZZo+F9jnb/viIUrrhlAiAbSWZJ+RVbDDr8wkQN6U6Sg=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
