sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        P25r4ajxKO8LeF5i7g8Vuw08FNXTnnHmRv7knh13pbQF+MeOjg0pOp5Qe8g0hLD9Kr1MJEeIEgSug/9i0A/Lo9dbqxjvn6yHJWV3xiLOX0jRg8CcSrC8tFZp1mKvkjYICILhCPT4AIBJmKSrm/dnebehvoYFDIrNyIeabbFIX/0XwGOpY2XtS9t+fVYmZXmUZY+j4GrroAL5evjY+fxplrdGurFfQtnwSOCOvzTKw+Y9w82mKFLyZfa4BZS4XmQgtiMitSiMwR9XkIYFH18Dquhfp2fmhk0dZ1RP2tnrLp8245x8IzrAHVUB497ebI5II0Dbk90xU/Osq1AgsZKLFYlirNm0wxWvUkjCNmkPcic8bopC/WJEXHlrodmh+IS/QGPo94b96ghMIaVNmcace+Zc3pmglf6/kM86ZozZz0xDlnjdsd96klHKre0fZstgkczaM2Zmz4QdIlTmrX6/bssd/yPzGzg8UnuGih0PRdcDelSBoUAsUh0fkGCPfjQGXVdZii1YfZrguIrm0JBTKvPto9YHeXoeNsVJQ9gP2B81lnayHg+KTdVlqt7MOutiBr6o3NkadT3akQR2U5FIovkSRfccMinWjT4SsXkzlkqPARsS7CVoN85tUAdtwkDxLWe3cCqSquT/Y2O4TSgFAoqgpPLjYK+YXuvPhg7MoLI=
    - secure: >-
        l/CR67I/989dZ90pHuzPh5KIqLVGacYsng+Mk2v1LFKDyIKM99aTKRlq/rhOzmf02uBduVQ/pZSni57oILPhmkZ2RpRM9wFjqRPL8QmeXeVjXUB84JZTQggtiKnCBhH7wTdj8P3ekaus2Liwrn3dDzKh5NAaKHQG544AJsNO7+VrGAY4aGZ/dMr5o1d4alVjST2y9/cI1dQAdWP4NwpK0E+q4LzBF50OVxMTNsei6sTFBrI5cv5Av0vakZzstPmWr9Q2Jj9Y1cDPXF2wo/k6E0eobYHvJ4z1rkgfQ3DmW60eJatRHQoK/BQSSz3NIqB4ESPQcN5EMhxqqcw54eHZE2zU3yd1aveDh0b+NUvlR+RcbNe5AxB377o1MLBmJtnUaiR1wy4gta/ci2sacO1AGiZwg/gLingFEirY79W6eAc/XuTQvXF5CVkhVMOoiw6ihFpM9Rf41T7NoyNWq3AU/H35C5GvhFBikT4Ew3aLLoScYdHe2w5f7GmjicgcLlRFESLTBVNGqZacSwSuJ87sMrRmZ/6qdq5y8SmQQ+63Pg2QtSq+IIEppln/IJoYqNyQi1XCMm77v7HEEm3ppxa2j4QZA4D1uvnSNLE+H1SjFnWHTCQOeT9pJXE8fIkoYGUJhfRL0mpaIm4TQleGqNl32AKJffS0YPLOjUW0ffS0y10=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
